export const NOTE_LENGTH_LIMIT = 200;

export const APP_NAME = "Neon Auth Demo";

export {
	HTTP_ACCEPTED,
	HTTP_BAD_GATEWAY,
	HTTP_BAD_REQUEST,
	HTTP_CONFLICT,
	HTTP_CREATED,
	HTTP_FORBIDDEN,
	HTTP_FOUND,
	HTTP_GATEWAY_TIMEOUT,
	HTTP_GONE,
	HTTP_INTERNAL_SERVER_ERROR,
	HTTP_METHOD_NOT_ALLOWED,
	HTTP_MOVED_PERMANENTLY,
	HTTP_NO_CONTENT,
	HTTP_NOT_ACCEPTABLE,
	HTTP_NOT_FOUND,
	HTTP_NOT_IMPLEMENTED,
	HTTP_NOT_MODIFIED,
	HTTP_OK,
	HTTP_PAYMENT_REQUIRED,
	HTTP_REQUEST_TIMEOUT,
	HTTP_SERVICE_UNAVAILABLE,
	HTTP_TOO_MANY_REQUESTS,
	HTTP_UNAUTHORIZED,
	HTTP_UNPROCESSABLE_ENTITY,
} from "./http";
